export const GAME_CONFIG = {
  movement: {
    walkSpeed: 5.2,
    sprintSpeed: 8.4,
    crouchSpeed: 2.8,
    crouchBlendIn: 13.5,
    crouchBlendOut: 16.0,
    combatCrouchBlendIn: 18.5,
    combatCrouchBlendOut: 21.5,
    crouchAcceleration: 18,
    crouchExitAcceleration: 20,
    combatCrouchAcceleration: 22,
    combatCrouchExitAcceleration: 24,
    acceleration: 15.5,
    sprintAcceleration: 10.5,
    turnAcceleration: 7.5,
    deceleration: 18,
    sprintBrakeDeceleration: 7.2,
    sprintSkidMinSpeed: 6.1,
    airAcceleration: 14,
    backpedalMultiplier: 0.80,
    strafeMultiplier: 0.92,
    sprintBlendStartSpeed: 4.8,
    sprintBlendIn: 7.5,
    sprintBlendOut: 9.5,
    turnResponse: 14,
    sprintTurnResponse: 9.5,
    turnLeanAmount: 0.22,
    maxTurnLean: 0.13,
    turnLeanResponse: 10,
    sprintBodyLean: 0.055,
    // SHIFT-scale tuning: 1.60m apex in 0.32s, then a brisk descent.
    jumpVelocity: 10,
    gravity: 31.25,
    fallGravity: 40,
    maxFallSpeed: 28,
    sprintJumpMultiplier: 1.05,
    jumpBuffer: 0.12,
    coyoteTime: 0.085,
    slideInitialSpeed: 10.2,
    slideEntryBoost: 1.2,
    slideDuration: 1.7,
    slideFriction: 4.4,
    slideLowSpeedFriction: 1.15,
    slideFlatTargetSpeed: 5.2,
    slideMinStartSpeed: 5.45,
    slideExitSpeed: 3.25,
    slideMaxSpeed: 13.5,
    slideSteering: 2.35,
    slideReverseBrake: 9.5,
    slideDownhillAcceleration: 11.5,
    slideDownhillFrictionScale: 0.35,
    slideUphillBrake: 14.0,
    radius: 0.45,
    standingHeight: 1.8,
    crouchHeight: 1.15
  },
  camera: {
    distance: 5.4,
    height: 1.6,
    shoulderOffset: 0.75,
    normalFov: 68,
    sprintFov: 74,
    sprintDistanceBoost: 0.24,
    slideFovBlend: 0.55,
    motionFovResponse: 7.5,
    sensitivity: 0.0024,
    pitchMin: -0.7,
    pitchMax: 1.1,
    collisionPadding: 0.22
  },
  weapons: {
    mechanicalAR: {
      junkStyle: 'stapleSlinger',
      junkPaint: 0xb84b3d,
      heldScale: 0.66,
      pickupScale: 0.86,
      visualWidthScale: 1.00,
      visualHeightScale: 1.00,
      visualLengthScale: 1.00,
      // Physical presentation benchmark: M4-class carbine proportions.
      // This is an original scavenged weapon, but its world-space footprint is
      // calibrated in meters so it cannot silently become SMG/sniper sized.
      massKg: 3.5,
      physicalSizeM: { width: 0.12, height: 0.26, length: 0.84 },

      stanceReadyX: 0.010,
      stanceReadyY: -0.090,
      stanceReadyZ: -0.105,
      stanceHipX: 0.006,
      stanceHipY: -0.045,
      stanceHipZ: -0.155,
      stanceAdsX: -0.006,
      stanceAdsY: -0.010,
      stanceAdsZ: -0.185,
      poseClass: 'ar',

      // Same stable shooter hierarchy used by the other hero weapons:
      // right/master hand owns the AR, left hand follows the front support point.
      masterHandCarry: true,
      supportHandIKLambda: 88,
      rightGripX: 0,
      rightGripY: -0.205,
      rightGripZ: 0.185,
      rightWristGripUp: 0.050,
      rightWristGripBack: 0.018,
      rightWristGripRight: 0.010,
      leftWristGripUp: 0.016,
      leftWristGripBack: 0.006,
      adsPoseMotionScale: 0.045,
      leftGripX: 0,
      leftGripY: -0.045,
      foregripZ: -0.345,
      recoilPoseScale: 0.11,
      shoulderHoldTime: 0.24,
      shoulderRaiseSpeed: 30,
      shoulderLowerSpeed: 11,
      shoulderPoseSpeed: 36,
      shoulderLowerPoseSpeed: 20,
      shoulderSupportIKLambda: 150,
      adsPoseInSpeed: 30,
      adsPoseOutSpeed: 21,

      combatGripForward: 0.170,
      combatGripRight: -0.014,
      combatGripUp: -0.052,
      adsGripForwardAdd: -0.014,
      adsGripRightAdd: -0.010,
      adsGripUpAdd: 0.022,
      hipFireAimPitch: -0.048,
      adsAimPitch: -0.014,
      hipFireAimRoll: -0.036,
      adsAimRoll: -0.008,
      carryPitch: -0.105,
      carryYaw: -0.022,
      carryRoll: -0.045,

      slot: 1,
      name: 'STAPLE-SLINGER AR',
      role: 'STABLE MID–FAR',
      automatic: true,
      ammoType: 'medium',

      // Preserve the existing Mechanical AR combat balance in this art pass.
      damage: 30,
      headshotMultiplier: 1.5,
      fireRate: 5.8,
      magazineSize: 20,
      reloadTime: 2.2,
      range: 105,
      falloffStart: 40,
      falloffEnd: 88,
      minDamageMultiplier: 0.72,
      hipBloom: 0.012,
      adsBloom: 0.0017,
      bloomPerShot: 0.0014,
      bloomDecay: 6.3,
      moveSpreadMult: 1.18,
      airSpreadMult: 2.35,
      crouchSpreadMult: 0.75,
      firstShotAccuracy: true,
      recoilPattern: [
        [0.013,0],
        [0.014,-0.001],
        [0.015,0.001],
        [0.016,-0.002],
        [0.016,0.002]
      ],
      // Fortnite Assault Rifle reference: low horizontal recoil relative
      // to vertical recoil, with First Shot Accuracy and bloom doing much of
      // the long-range accuracy work.
      fortniteRecoil: {
        vertical: 3.15,
        horizontal: 0.25,
        seed: 31,
        verticalPattern: [0.78, 0.90, 0.98, 1.03, 1.07, 1.09, 1.10, 1.10],
        earlyRampShots: 6,
        earlyRampPerShot: 0.018,
        horizontalRampShots: 5,
        horizontalRampPerShot: 0.025
      },
      recoilResetDelay: 0.62,
      bloomSettleDelay: 0.34,
      bloomSettleSnap: 0.00016,
      firstShotResetTime: 0.58,
      firstShotAccuracySpread: 0,
      aimRecoilAttack: 64,
      recoilRecovery: 10.5,
      recoilAttack: 68,
      recoilMaxPitch: 0.14,
      recoilMaxYaw: 0.040,
      adsRecoilMultiplier: 0.94,
      aimRecoilPitchFraction: 0.76,
      aimRecoilYawFraction: 0.70,
      visualRecoilFraction: 0.24,
      sustainedFirePerShot: 0.18,
      sustainedFireRecovery: 3.6,
      weaponKickImpulse: 15.5,
      adsWeaponKickImpulse: 12.5,
      weaponRecoilPitch: 0.014,
      weaponRecoilYaw: 0.0015,
      weaponRecoilRoll: 0.0025,
      weaponRecoilRecovery: 16,
      weaponRecoilMaxPitch: 0.080,
      weaponRecoilMaxYaw: 0.012,
      weaponRecoilMaxRoll: 0.014,
      visualKick: 0.105,
      sway: 0.0042,
      bob: 0.014,
      adsFov: 52,
      adsDistance: 2.95,
      adsShoulderOffset: 0.86,
      reticle: 'rifle',
      reticleMinGap: 5,
      reticleMaxGap: 18,
      pellets: 1,
      color: 0xc65343,
      modelLength: 0.86,
      sound: {
        pitch: 118,
        duration: 0.095,
        noise: 0.48,
        gain: 0.23
      }
    },
    pumpShotgun: {
      junkStyle: 'bugSprayer',
      junkPaint: 0xb84c38,
      heldScale: 0.74,
      pickupScale: 0.90,
      visualWidthScale: 1.10,
      visualHeightScale: 1.06,
      visualLengthScale: 1.02,
      // Full-length pump silhouette, slightly heavier than the real-world
      // benchmark because the Bug-Sprayer carries a bulky tank assembly.
      massKg: 3.8,
      physicalSizeM: { width: 0.20, height: 0.32, length: 1.03 },

      stanceReadyX: 0.012,
      stanceReadyY: -0.102,
      stanceReadyZ: -0.118,
      stanceHipX: 0.008,
      stanceHipY: -0.054,
      stanceHipZ: -0.168,
      stanceAdsX: -0.004,
      stanceAdsY: -0.016,
      stanceAdsZ: -0.196,
      poseClass: 'shotgun',

      // Stable shooter hierarchy: right/master hand owns the weapon,
      // left/support hand follows the pump grip with IK.
      masterHandCarry: true,
      supportHandIKLambda: 92,
      rightGripX: 0,
      rightGripY: -0.205,
      rightGripZ: 0.205,
      rightWristGripUp: 0.052,
      rightWristGripBack: 0.020,
      rightWristGripRight: 0.010,
      leftWristGripUp: 0.018,
      leftWristGripBack: 0.008,
      adsPoseMotionScale: 0.040,
      leftGripX: 0,
      leftGripY: -0.095,
      foregripZ: -0.515,
      shoulderHoldTime: 0.42,
      shoulderRaiseSpeed: 28,
      shoulderLowerSpeed: 9.5,
      shoulderPoseSpeed: 34,
      shoulderLowerPoseSpeed: 18,
      shoulderSupportIKLambda: 158,
      adsPoseInSpeed: 27,
      adsPoseOutSpeed: 18,

      combatGripForward: 0.175,
      combatGripRight: -0.004,
      combatGripUp: -0.070,
      adsGripForwardAdd: -0.012,
      adsGripRightAdd: -0.008,
      adsGripUpAdd: 0.020,
      hipFireAimPitch: -0.055,
      adsAimPitch: -0.018,
      hipFireAimRoll: -0.040,
      adsAimRoll: -0.010,
      carryPitch: -0.115,
      carryYaw: -0.015,
      carryRoll: -0.045,

      slot: 3,
      name: 'BUG-SPRAYER SHOTGUN',
      role: 'HEAVY CLOSE BURST',
      automatic: false,
      ammoType: 'shells',

      // Fortnite Legendary Hammer Pump benchmark:
      // 103 body, 190.55 headshot (1.85x), 0.7 RPS,
      // 6-shell magazine, 4.73 s reload.
      damage: 103,
      headshotMultiplier: 1.85,
      fireRate: 0.7,
      magazineSize: 6,
      reloadTime: 4.73,

      // Keep SHIFT's world-unit falloff/spread model while matching
      // Fortnite's headline weapon stats above.
      range: 22,
      falloffStart: 6,
      falloffEnd: 16,
      minDamageMultiplier: 0.18,
      hipBloom: 0.068,
      adsBloom: 0.046,
      // The fired reticle blooms visibly, then fully settles before the next
      // legal pump shot.
      bloomPerShot: 0.026,
      bloomDecay: 4.2,
      moveSpreadMult: 1.08,
      airSpreadMult: 1.55,
      crouchSpreadMult: 0.90,
      firstShotAccuracy: false,
      recoilPattern: [[0.052,0.006], [0.050,-0.005]],
      // Fortnite pump-family reference: one large vertical impulse with
      // noticeable but secondary horizontal recoil, fully recovering between
      // the deliberately slow shots.
      fortniteRecoil: {
        vertical: 7.2,
        horizontal: 2.0,
        seed: 73,
        verticalPattern: [1.0, 0.98],
        horizontalRampShots: 0,
        horizontalRampPerShot: 0
      },
      recoilResetDelay: 0.95,
      bloomSettleDelay: 0.52,
      bloomSettleSnap: 0.00022,
      aimRecoilAttack: 76,
      recoilRecovery: 7.2,
      recoilAttack: 74,
      recoilMaxPitch: 0.18,
      recoilMaxYaw: 0.070,
      adsRecoilMultiplier: 0.96,
      aimRecoilPitchFraction: 0.80,
      aimRecoilYawFraction: 0.72,
      visualRecoilFraction: 0.24,
      sustainedFirePerShot: 0.46,
      sustainedFireRecovery: 5.4,
      weaponKickImpulse: 21.5,
      adsWeaponKickImpulse: 18.0,
      weaponRecoilPitch: 0.045,
      weaponRecoilYaw: 0.012,
      weaponRecoilRoll: 0.010,
      weaponRecoilRecovery: 10.5,
      weaponRecoilMaxPitch: 0.12,
      weaponRecoilMaxYaw: 0.028,
      weaponRecoilMaxRoll: 0.030,
      visualKick: 0.31,
      recoilPoseScale: 0.32,
      pumpAction: true,
      pumpTravel: 0.16,
      hidePelletTracers: true,
      sway: 0.0035,
      bob: 0.011,
      adsFov: 60,
      adsDistance: 4.25,
      adsShoulderOffset: 0.84,
      reticle: 'pump',
      reticleMinGap: 14,
      reticleMaxGap: 29,
      pellets: 10,
      color: 0xc95743,
      modelLength: 0.82,
      sound: {
        pitch: 64,
        duration: 0.22,
        noise: 1.0,
        gain: 0.36
      }
    },
    marksmanSniper: {
      junkStyle: 'antenna',
      junkPaint: 0xa94c37,
      heldScale: 0.60,
      pickupScale: 0.84,
      visualWidthScale: 0.96,
      visualHeightScale: 0.98,
      visualLengthScale: 1.06,
      // Heavy precision-rifle class. The 1.14 m envelope follows a compact
      // .50-cal benchmark while keeping SHIFT's original antenna silhouette.
      massKg: 9.5,
      physicalSizeM: { width: 0.16, height: 0.30, length: 1.14 },

      stanceReadyX: 0.018,
      stanceReadyY: -0.165,
      stanceReadyZ: -0.082,
      stanceHipX: 0.004,
      stanceHipY: -0.066,
      stanceHipZ: -0.202,
      stanceAdsX: -0.010,
      stanceAdsY: -0.024,
      stanceAdsZ: -0.232,
      poseClass: 'sniper',
      masterHandCarry: true,
      supportHandIKLambda: 96,
      rightGripX: 0,
      rightGripY: -0.205,
      rightGripZ: 0.190,
      rightWristGripUp: 0.050,
      rightWristGripBack: 0.022,
      rightWristGripRight: 0.010,
      leftWristGripUp: 0.017,
      leftWristGripBack: 0.007,
      adsPoseMotionScale: 0.030,
      leftGripX: 0,
      leftGripY: -0.060,
      foregripZ: -0.365,
      shoulderHoldTime: 0.62,
      shoulderRaiseSpeed: 24,
      shoulderLowerSpeed: 7.2,
      shoulderPoseSpeed: 27,
      shoulderLowerPoseSpeed: 14,
      shoulderSupportIKLambda: 154,
      adsPoseInSpeed: 20,
      adsPoseOutSpeed: 13,
      combatGripForward: 0.220,
      combatGripRight: -0.018,
      combatGripUp: -0.060,
      adsGripForwardAdd: -0.010,
      adsGripRightAdd: -0.008,
      adsGripUpAdd: 0.024,
      hipFireAimPitch: -0.050,
      adsAimPitch: -0.010,
      hipFireAimRoll: -0.030,
      adsAimRoll: -0.004,
      carryPitch: -0.185,
      carryYaw: -0.040,
      carryRoll: -0.095,
      slot: 5, name: 'MARKSMAN SNIPER', role: '2-SHOT LONG RANGE', automatic: false, ammoType: 'heavy',
      damage: 110, headshotMultiplier: 2, fireRate: 0.75, magazineSize: 2, reloadTime: 3.0,
      range: 160, falloffStart: 105, falloffEnd: 155, minDamageMultiplier: 0.90,
      hipBloom: 0.115, adsBloom: 0.00035, bloomPerShot: 0.004, bloomDecay: 2.8,
      moveSpreadMult: 3.0, airSpreadMult: 5.0, crouchSpreadMult: 0.72, firstShotAccuracy: false,
      recoilPattern: [[0.070,0.004],[0.068,-0.004]],
      // Fortnite Heavy Sniper reference: strongest single-shot vertical
      // recoil of this loadout, small horizontal deviation, slower recovery.
      fortniteRecoil: {
        vertical: 8.5,
        horizontal: 2.0,
        seed: 113,
        verticalPattern: [1.0, 0.98],
        horizontalRampShots: 0,
        horizontalRampPerShot: 0
      },
      recoilResetDelay: 1.10,
      bloomSettleDelay: 0.64,
      bloomSettleSnap: 0.00020,
      aimRecoilAttack: 70,
      recoilRecovery: 5.8, recoilAttack: 72, recoilMaxPitch: 0.21, recoilMaxYaw: 0.070,
      adsRecoilMultiplier: 1.0, aimRecoilPitchFraction: 0.84, aimRecoilYawFraction: 0.78,
      visualRecoilFraction: 0.22, sustainedFirePerShot: 0.50,
      sustainedFireRecovery: 4.8, weaponKickImpulse: 20.0, adsWeaponKickImpulse: 18.0,
      weaponRecoilPitch: 0.055, weaponRecoilYaw: 0.013, weaponRecoilRoll: 0.012,
      weaponRecoilRecovery: 8.0, weaponRecoilMaxPitch: 0.14, weaponRecoilMaxYaw: 0.030,
      weaponRecoilMaxRoll: 0.032, visualKick: 0.36, sway: 0.0027, bob: 0.008,
      adsFov: 24, adsDistance: 0.10, adsShoulderOffset: 0,
      reticle: 'sniper', reticleMinGap: 8, reticleMaxGap: 30, scope: true,
      pellets: 1, color: 0x7356b6, modelLength: 1.10,
      sound: { pitch: 52, duration: 0.24, noise: 0.78, gain: 0.37 }
    },
    compactSMG: {
      junkStyle: 'tapeRattler',
      junkPaint: 0xd88a2f,
      heldScale: 0.66,
      pickupScale: 0.82,
      visualWidthScale: 0.94,
      visualHeightScale: 0.94,
      visualLengthScale: 0.90,
      // Compact SMG envelope: substantially shorter/lighter than the AR.
      // Width stays stylized because the signature tape wheel is intentional.
      massKg: 2.8,
      physicalSizeM: { width: 0.24, height: 0.30, length: 0.66 },

      stanceReadyX: 0.014,
      stanceReadyY: -0.080,
      stanceReadyZ: -0.082,
      stanceHipX: 0.010,
      stanceHipY: -0.034,
      stanceHipZ: -0.126,
      stanceAdsX: 0.002,
      stanceAdsY: -0.004,
      stanceAdsZ: -0.152,
      poseClass: 'smg',

      // Stable hero-weapon rig: right/master hand owns the compact SMG,
      // left/support hand follows the front of the dispenser body.
      masterHandCarry: true,
      supportHandIKLambda: 90,
      rightGripX: 0,
      rightGripY: -0.205,
      rightGripZ: 0.165,
      rightWristGripUp: 0.047,
      rightWristGripBack: 0.016,
      rightWristGripRight: 0.009,
      leftWristGripUp: 0.015,
      leftWristGripBack: 0.005,
      adsPoseMotionScale: 0.050,
      leftGripX: 0,
      leftGripY: -0.040,
      foregripZ: -0.285,
      recoilPoseScale: 0.07,
      shoulderHoldTime: 0.18,
      shoulderRaiseSpeed: 34,
      shoulderLowerSpeed: 13,
      shoulderPoseSpeed: 40,
      shoulderLowerPoseSpeed: 22,
      shoulderSupportIKLambda: 170,
      adsPoseInSpeed: 34,
      adsPoseOutSpeed: 24,

      combatGripForward: 0.145,
      combatGripRight: 0.004,
      combatGripUp: -0.070,
      adsGripForwardAdd: -0.013,
      adsGripRightAdd: -0.009,
      adsGripUpAdd: 0.019,
      hipFireAimPitch: -0.052,
      adsAimPitch: -0.018,
      hipFireAimRoll: -0.044,
      adsAimRoll: -0.012,
      carryPitch: -0.120,
      carryYaw: -0.035,
      carryRoll: -0.055,

      slot: 2,
      name: 'TAPE-RATTLER SMG',
      role: 'VERY FAST CLOSE',
      automatic: true,
      ammoType: 'light',

      // Preserve Compact SMG balance in this art/identity pass.
      damage: 17,
      headshotMultiplier: 1.5,
      fireRate: 12,
      magazineSize: 30,
      reloadTime: 2.5,
      range: 60,
      falloffStart: 16,
      falloffEnd: 40,
      minDamageMultiplier: 0.42,
      hipBloom: 0.019,
      adsBloom: 0.0075,
      bloomPerShot: 0.0036,
      bloomDecay: 7.8,
      moveSpreadMult: 1.38,
      airSpreadMult: 2.1,
      crouchSpreadMult: 0.86,
      firstShotAccuracy: false,
      recoilPattern: [
        [0.005,0.002],
        [0.005,-0.002],
        [0.006,0.003],
        [0.006,-0.003],
        [0.007,0.002]
      ],
      // Fortnite Machine-SMG reference: small per-shot vertical rise but
      // much more lateral recoil relative to vertical than the AR.
      fortniteRecoil: {
        vertical: 1.8,
        horizontal: 1.45,
        seed: 157,
        verticalPattern: [0.80, 0.94, 1.06, 0.90, 1.08, 1.00],
        horizontalRampShots: 8,
        horizontalRampPerShot: 0.018
      },
      recoilResetDelay: 0.34,
      bloomSettleDelay: 0.20,
      bloomSettleSnap: 0.00020,
      aimRecoilAttack: 80,
      recoilRecovery: 18,
      recoilAttack: 72,
      recoilMaxPitch: 0.10,
      recoilMaxYaw: 0.085,
      adsRecoilMultiplier: 0.92,
      aimRecoilPitchFraction: 0.72,
      aimRecoilYawFraction: 0.80,
      visualRecoilFraction: 0.28,
      sustainedFirePerShot: 0.13,
      sustainedFireRecovery: 5.2,
      weaponKickImpulse: 14.5,
      adsWeaponKickImpulse: 11.5,
      weaponRecoilPitch: 0.008,
      weaponRecoilYaw: 0.0065,
      weaponRecoilRoll: 0.0045,
      weaponRecoilRecovery: 20,
      weaponRecoilMaxPitch: 0.055,
      weaponRecoilMaxYaw: 0.026,
      weaponRecoilMaxRoll: 0.018,
      visualKick: 0.047,
      sway: 0.0075,
      bob: 0.026,
      adsFov: 60,
      adsDistance: 3.85,
      adsShoulderOffset: 0.92,
      reticle: 'smg',
      reticleMinGap: 7,
      reticleMaxGap: 24,
      pellets: 1,
      color: 0xe2a13a,
      modelLength: 0.60,
      tapeWheelSpin: true,
      sound: {
        pitch: 205,
        duration: 0.045,
        noise: 0.42,
        gain: 0.15
      }
    }
  },
  tinFang: {
    meleeDamage: 40,
    clawDamage: 22,
    throwBodyDamage: 90,
    meleeRange: 1.85,
    primeThreshold: 0.28,
    fullChargeTime: 0.82,
    minThrowSpeed: 21,
    maxThrowSpeed: 29,
    projectileGravity: 8.5,
    projectileLifetime: 4.8,
    releaseDuration: 0.48,
    releaseMoment: 0.42,
    aimRange: 75,
    aimFov: 54,
    aimDistance: 4.15,
    aimShoulderOffset: 0.96,
    // Probe from 1.42m up to 2.67m, including the dining table underside (2.55m).
    compactAimClearance: 1.25,
    compactAimShoulderOffset: 0.82,
    fallGravity: 15,
    bounceRestitution: 0.30,
    recoveryRadius: 1.15,
    recoveryVerticalTolerance: 1.65
  },
  playerCombat: {
    maxHealth: 100,
    maxShield: 100,
    respawnDelay: 2.5
  },
  bot: {
    maxHealth: 100,
    maxShield: 100,
    moveSpeed: 3.4,
    detectionRange: 28,
    attackRange: 15,
    preferredRange: 9,
    damage: 12,
    fireRate: 2.2,
    respawnDelay: 2.5,
    searchDuration: 2.2,
    radius: 0.42
  }
};

export const WEAPON_ORDER = [
  'mechanicalAR',
  'pumpShotgun',
  'marksmanSniper',
  'compactSMG'
];
