export const GAME_CONFIG = {
  movement: {
    walkSpeed: 5.2,
    sprintSpeed: 8.4,
    crouchSpeed: 2.8,
    crouchBlendIn: 13.5,
    crouchBlendOut: 16.0,
    combatCrouchBlendIn: 18.5,
    combatCrouchBlendOut: 21.5,
    crouchAcceleration: 18,
    crouchExitAcceleration: 20,
    combatCrouchAcceleration: 22,
    combatCrouchExitAcceleration: 24,
    acceleration: 15.5,
    sprintAcceleration: 10.5,
    turnAcceleration: 7.5,
    deceleration: 18,
    sprintBrakeDeceleration: 7.2,
    sprintSkidMinSpeed: 6.1,
    airAcceleration: 14,
    backpedalMultiplier: 0.80,
    strafeMultiplier: 0.92,
    sprintBlendStartSpeed: 4.8,
    sprintBlendIn: 7.5,
    sprintBlendOut: 9.5,
    turnResponse: 14,
    sprintTurnResponse: 9.5,
    turnLeanAmount: 0.22,
    maxTurnLean: 0.13,
    turnLeanResponse: 10,
    sprintBodyLean: 0.055,
    // SHIFT-scale tuning: 1.60m apex in 0.32s, then a brisk descent.
    jumpVelocity: 10,
    gravity: 31.25,
    fallGravity: 40,
    maxFallSpeed: 28,
    sprintJumpMultiplier: 1.05,
    jumpBuffer: 0.12,
    coyoteTime: 0.085,
    slideInitialSpeed: 10.2,
    slideEntryBoost: 1.2,
    slideDuration: 1.7,
    slideFriction: 4.4,
    slideLowSpeedFriction: 1.15,
    slideFlatTargetSpeed: 5.2,
    slideMinStartSpeed: 5.45,
    slideExitSpeed: 3.25,
    slideMaxSpeed: 13.5,
    slideSteering: 2.35,
    slideReverseBrake: 9.5,
    slideDownhillAcceleration: 11.5,
    slideDownhillFrictionScale: 0.35,
    slideUphillBrake: 14.0,
    radius: 0.45,
    standingHeight: 1.8,
    crouchHeight: 1.15
  },
  camera: {
    distance: 5.4,
    height: 1.6,
    shoulderOffset: 0.75,
    normalFov: 68,
    sprintFov: 74,
    sprintDistanceBoost: 0.24,
    slideFovBlend: 0.55,
    motionFovResponse: 7.5,
    sensitivity: 0.0024,
    pitchMin: -0.7,
    pitchMax: 1.1,
    collisionPadding: 0.22
  },
  weapons: {
    mechanicalAR: {
      junkStyle: 'stapleSlinger',
      junkPaint: 0xb84b3d,
      heldScale: 0.66,
      pickupScale: 0.86,

      // Same stable shooter hierarchy used by the other hero weapons:
      // right/master hand owns the AR, left hand follows the front support point.
      masterHandCarry: true,
      supportHandIKLambda: 105,
      rightGripX: 0,
      rightGripY: -0.205,
      rightGripZ: 0.185,
      leftGripX: 0,
      leftGripY: -0.045,
      foregripZ: -0.345,
      recoilPoseScale: 0.11,

      combatGripForward: 0.170,
      combatGripRight: -0.014,
      combatGripUp: -0.052,
      carryPitch: -0.105,
      carryYaw: -0.022,
      carryRoll: -0.045,

      slot: 1,
      name: 'STAPLE-SLINGER AR',
      role: 'STABLE MID–FAR',
      automatic: true,
      ammoType: 'medium',

      // Preserve the existing Mechanical AR combat balance in this art pass.
      damage: 30,
      headshotMultiplier: 1.5,
      fireRate: 5.8,
      magazineSize: 20,
      reloadTime: 2.2,
      range: 105,
      falloffStart: 40,
      falloffEnd: 88,
      minDamageMultiplier: 0.72,
      hipBloom: 0.012,
      adsBloom: 0.0017,
      bloomPerShot: 0.0014,
      bloomDecay: 6.3,
      moveSpreadMult: 1.18,
      airSpreadMult: 2.35,
      crouchSpreadMult: 0.75,
      firstShotAccuracy: true,
      recoilPattern: [
        [0.013,0],
        [0.014,-0.001],
        [0.015,0.001],
        [0.016,-0.002],
        [0.016,0.002]
      ],
      recoilRecovery: 10.5,
      recoilAttack: 38,
      recoilMaxPitch: 0.16,
      recoilMaxYaw: 0.070,
      adsRecoilMultiplier: 0.60,
      sustainedRecoilScale: 0.34,
      sustainedFirePerShot: 0.20,
      sustainedFireRecovery: 3.2,
      weaponKickImpulse: 16.0,
      adsWeaponKickImpulse: 11.5,
      weaponRecoilPitch: 0.018,
      weaponRecoilYaw: 0.006,
      weaponRecoilRoll: 0.005,
      weaponRecoilRecovery: 15,
      weaponRecoilMaxPitch: 0.095,
      weaponRecoilMaxYaw: 0.024,
      weaponRecoilMaxRoll: 0.020,
      visualKick: 0.105,
      mass: 1.16,
      sway: 0.0042,
      bob: 0.014,
      adsFov: 52,
      adsDistance: 2.95,
      adsShoulderOffset: 0.86,
      reticle: 'rifle',
      reticleMinGap: 5,
      reticleMaxGap: 18,
      pellets: 1,
      color: 0xc65343,
      modelLength: 0.86,
      sound: {
        pitch: 118,
        duration: 0.095,
        noise: 0.48,
        gain: 0.23
      }
    },
    pumpShotgun: {
      junkStyle: 'bugSprayer',
      junkPaint: 0xb84c38,
      heldScale: 0.67,
      pickupScale: 0.86,

      // Stable shooter hierarchy: right/master hand owns the weapon,
      // left/support hand follows the pump grip with IK.
      masterHandCarry: true,
      supportHandIKLambda: 120,
      rightGripX: 0,
      rightGripY: -0.205,
      rightGripZ: 0.205,
      leftGripX: 0,
      leftGripY: -0.095,
      foregripZ: -0.515,

      combatGripForward: 0.175,
      combatGripRight: -0.004,
      combatGripUp: -0.070,
      carryPitch: -0.115,
      carryYaw: -0.015,
      carryRoll: -0.045,

      slot: 3,
      name: 'BUG-SPRAYER SHOTGUN',
      role: 'HEAVY CLOSE BURST',
      automatic: false,
      ammoType: 'shells',

      // Fortnite Legendary Hammer Pump benchmark:
      // 103 body, 190.55 headshot (1.85x), 0.7 RPS,
      // 6-shell magazine, 4.73 s reload.
      damage: 103,
      headshotMultiplier: 1.85,
      fireRate: 0.7,
      magazineSize: 6,
      reloadTime: 4.73,

      // Keep SHIFT's world-unit falloff/spread model while matching
      // Fortnite's headline weapon stats above.
      range: 22,
      falloffStart: 6,
      falloffEnd: 16,
      minDamageMultiplier: 0.18,
      hipBloom: 0.068,
      adsBloom: 0.046,
      // The fired reticle blooms visibly, then fully settles before the next
      // legal pump shot.
      bloomPerShot: 0.026,
      bloomDecay: 4.2,
      moveSpreadMult: 1.08,
      airSpreadMult: 1.55,
      crouchSpreadMult: 0.90,
      firstShotAccuracy: false,
      recoilPattern: [[0.052,0.006], [0.050,-0.005]],
      recoilRecovery: 7.0,
      recoilAttack: 52,
      recoilMaxPitch: 0.22,
      recoilMaxYaw: 0.095,
      adsRecoilMultiplier: 0.76,
      sustainedRecoilScale: 0,
      sustainedFirePerShot: 0.52,
      sustainedFireRecovery: 5.0,
      weaponKickImpulse: 21.0,
      adsWeaponKickImpulse: 17.0,
      weaponRecoilPitch: 0.070,
      weaponRecoilYaw: 0.012,
      weaponRecoilRoll: 0.014,
      weaponRecoilRecovery: 10,
      weaponRecoilMaxPitch: 0.14,
      weaponRecoilMaxYaw: 0.030,
      weaponRecoilMaxRoll: 0.035,
      visualKick: 0.31,
      recoilPoseScale: 0.32,
      pumpAction: true,
      pumpTravel: 0.16,
      hidePelletTracers: true,
      mass: 1.34,
      sway: 0.0035,
      bob: 0.011,
      adsFov: 60,
      adsDistance: 4.25,
      adsShoulderOffset: 0.84,
      reticle: 'pump',
      reticleMinGap: 14,
      reticleMaxGap: 29,
      pellets: 10,
      color: 0xc95743,
      modelLength: 0.82,
      sound: {
        pitch: 64,
        duration: 0.22,
        noise: 1.0,
        gain: 0.36
      }
    },
    marksmanSniper: {
      junkStyle: 'antenna',
      junkPaint: 0xa94c37,
      heldScale: 0.58,
      pickupScale: 0.82,
      masterHandCarry: true,
      supportHandIKLambda: 150,
      rightGripX: 0,
      rightGripY: -0.205,
      rightGripZ: 0.190,
      leftGripX: 0,
      leftGripY: -0.060,
      foregripZ: -0.365,
      combatGripForward: 0.220,
      combatGripRight: -0.018,
      combatGripUp: -0.060,
      carryPitch: -0.105,
      carryYaw: -0.010,
      carryRoll: -0.040,
      slot: 5, name: 'MARKSMAN SNIPER', role: '2-SHOT LONG RANGE', automatic: false, ammoType: 'heavy',
      damage: 110, headshotMultiplier: 2, fireRate: 0.75, magazineSize: 2, reloadTime: 3.0,
      range: 160, falloffStart: 105, falloffEnd: 155, minDamageMultiplier: 0.90,
      hipBloom: 0.115, adsBloom: 0.00035, bloomPerShot: 0.004, bloomDecay: 2.8,
      moveSpreadMult: 3.0, airSpreadMult: 5.0, crouchSpreadMult: 0.72, firstShotAccuracy: false,
      recoilPattern: [[0.070,0.004],[0.068,-0.004]],
      recoilRecovery: 6.0, recoilAttack: 48, recoilMaxPitch: 0.24, recoilMaxYaw: 0.085,
      adsRecoilMultiplier: 0.72, sustainedRecoilScale: 0, sustainedFirePerShot: 0.55,
      sustainedFireRecovery: 4.5, weaponKickImpulse: 19.0, adsWeaponKickImpulse: 15.5,
      weaponRecoilPitch: 0.082, weaponRecoilYaw: 0.009, weaponRecoilRoll: 0.010,
      weaponRecoilRecovery: 8.5, weaponRecoilMaxPitch: 0.15, weaponRecoilMaxYaw: 0.026,
      weaponRecoilMaxRoll: 0.030, visualKick: 0.36, mass: 1.58, sway: 0.0027, bob: 0.008,
      adsFov: 24, adsDistance: 0.10, adsShoulderOffset: 0,
      reticle: 'sniper', reticleMinGap: 8, reticleMaxGap: 30, scope: true,
      pellets: 1, color: 0x7356b6, modelLength: 1.10,
      sound: { pitch: 52, duration: 0.24, noise: 0.78, gain: 0.37 }
    },
    compactSMG: {
      junkStyle: 'tapeRattler',
      junkPaint: 0xd88a2f,
      heldScale: 0.70,
      pickupScale: 0.88,

      // Stable hero-weapon rig: right/master hand owns the compact SMG,
      // left/support hand follows the front of the dispenser body.
      masterHandCarry: true,
      supportHandIKLambda: 115,
      rightGripX: 0,
      rightGripY: -0.205,
      rightGripZ: 0.165,
      leftGripX: 0,
      leftGripY: -0.040,
      foregripZ: -0.285,
      recoilPoseScale: 0.07,

      combatGripForward: 0.145,
      combatGripRight: 0.004,
      combatGripUp: -0.070,
      carryPitch: -0.120,
      carryYaw: -0.035,
      carryRoll: -0.055,

      slot: 2,
      name: 'TAPE-RATTLER SMG',
      role: 'VERY FAST CLOSE',
      automatic: true,
      ammoType: 'light',

      // Preserve Compact SMG balance in this art/identity pass.
      damage: 17,
      headshotMultiplier: 1.5,
      fireRate: 12,
      magazineSize: 30,
      reloadTime: 2.5,
      range: 60,
      falloffStart: 16,
      falloffEnd: 40,
      minDamageMultiplier: 0.42,
      hipBloom: 0.019,
      adsBloom: 0.0075,
      bloomPerShot: 0.0036,
      bloomDecay: 7.8,
      moveSpreadMult: 1.38,
      airSpreadMult: 2.1,
      crouchSpreadMult: 0.86,
      firstShotAccuracy: false,
      recoilPattern: [
        [0.005,0.002],
        [0.005,-0.002],
        [0.006,0.003],
        [0.006,-0.003],
        [0.007,0.002]
      ],
      recoilRecovery: 17,
      recoilAttack: 46,
      recoilMaxPitch: 0.115,
      recoilMaxYaw: 0.075,
      adsRecoilMultiplier: 0.54,
      sustainedRecoilScale: 0.24,
      sustainedFirePerShot: 0.14,
      sustainedFireRecovery: 4.6,
      weaponKickImpulse: 15.0,
      adsWeaponKickImpulse: 10.5,
      weaponRecoilPitch: 0.009,
      weaponRecoilYaw: 0.005,
      weaponRecoilRoll: 0.0045,
      weaponRecoilRecovery: 19,
      weaponRecoilMaxPitch: 0.065,
      weaponRecoilMaxYaw: 0.022,
      weaponRecoilMaxRoll: 0.018,
      visualKick: 0.047,
      mass: 0.74,
      sway: 0.0075,
      bob: 0.026,
      adsFov: 60,
      adsDistance: 3.85,
      adsShoulderOffset: 0.92,
      reticle: 'smg',
      reticleMinGap: 7,
      reticleMaxGap: 24,
      pellets: 1,
      color: 0xe2a13a,
      modelLength: 0.60,
      tapeWheelSpin: true,
      sound: {
        pitch: 205,
        duration: 0.045,
        noise: 0.42,
        gain: 0.15
      }
    }
  },
  tinFang: {
    meleeDamage: 40,
    clawDamage: 22,
    throwBodyDamage: 90,
    meleeRange: 1.85,
    primeThreshold: 0.28,
    fullChargeTime: 0.82,
    minThrowSpeed: 21,
    maxThrowSpeed: 29,
    projectileGravity: 8.5,
    projectileLifetime: 4.8,
    releaseDuration: 0.48,
    releaseMoment: 0.42,
    aimRange: 75,
    aimFov: 54,
    aimDistance: 4.15,
    aimShoulderOffset: 0.96,
    // Probe from 1.42m up to 2.67m, including the dining table underside (2.55m).
    compactAimClearance: 1.25,
    compactAimShoulderOffset: 0.82,
    fallGravity: 15,
    bounceRestitution: 0.30,
    recoveryRadius: 1.15,
    recoveryVerticalTolerance: 1.65
  },
  playerCombat: {
    maxHealth: 100,
    maxShield: 100,
    respawnDelay: 2.5
  },
  bot: {
    maxHealth: 100,
    maxShield: 100,
    moveSpeed: 3.4,
    detectionRange: 28,
    attackRange: 15,
    preferredRange: 9,
    damage: 12,
    fireRate: 2.2,
    respawnDelay: 2.5,
    searchDuration: 2.2,
    radius: 0.42
  }
};

export const WEAPON_ORDER = [
  'mechanicalAR',
  'pumpShotgun',
  'marksmanSniper',
  'compactSMG'
];
